workflows:
  ios-build-ipa:
    name: Build IPA
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "NextcloudTalk.xcworkspace"
        XCODE_SCHEME: "NextcloudTalk"
        BUNDLE_ID: "com.decoder.Talk"
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: development
        bundle_identifier: com.decoder.Talk
    scripts:
      - name: Install dependencies
        script: |
          pod install

      - name: Disable localization script
        script: |
          # Prevent generate-localizable-strings-file.sh from failing
          chmod -x generate-localizable-strings-file.sh || true

      - name: Set up keychain
        script: |
          keychain initialize

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_DEVELOPMENT \
            --create

      - name: Add certs to keychain
        script: |
          keychain add-certificates

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build archive
        script: |
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/app.xcarchive \
            -allowProvisioningUpdates

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/app.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa

    artifacts:
      - $CM_BUILD_DIR/app.xcarchive
      - $CM_BUILD_DIR/ipa/*.ipa
