workflows:
  ios-build-ipa:
    name: Build IPA
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "NextcloudTalk.xcworkspace"
        XCODE_SCHEME: "NextcloudTalk"
        BUNDLE_ID: "com.decoder.Talk"
        # Set your Apple ID for automatic signing
        APPLE_ID: $APPLE_ID
        APP_SPECIFIC_PASSWORD: $APP_SPECIFIC_PASSWORD
        TEAM_ID: $TEAM_ID
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          pod install

      - name: Disable localization script
        script: |
          chmod -x generate-localizable-strings-file.sh || true

      - name: Build archive with automatic signing
        script: |
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/app.xcarchive \
            -allowProvisioningUpdates \
            -authenticationKeyPath $CM_BUILD_DIR/AuthKey.p8 \
            -authenticationKeyID $APP_STORE_CONNECT_KEY_IDENTIFIER \
            -authenticationKeyIssuerID $APP_STORE_CONNECT_ISSUER_ID \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=$TEAM_ID || echo "Build with signing failed, trying without signing..."

      - name: Build without signing (fallback)
        script: |
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/app.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/app.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa || echo "IPA export failed, creating manually..."

      - name: Remove code signature for sideloading
        script: |
          echo "Preparing IPA for AltStore/Sideloadly sideloading"
          cd $CM_BUILD_DIR

          APP_PATH="app.xcarchive/Products/Applications/NextcloudTalk.app"

          if [ -d "$APP_PATH" ]; then
            # Remove existing code signature so AltStore/Sideloadly can re-sign
            echo "Removing embedded.mobileprovision and _CodeSignature"
            rm -rf "$APP_PATH/embedded.mobileprovision"
            rm -rf "$APP_PATH/_CodeSignature"

            # Remove code signature from all frameworks and plugins
            find "$APP_PATH" -name "_CodeSignature" -type d -exec rm -rf {} + 2>/dev/null || true
            find "$APP_PATH" -name "embedded.mobileprovision" -exec rm -f {} + 2>/dev/null || true

            echo "Code signature removed successfully"
          fi

      - name: Create unsigned IPA for sideloading
        script: |
          if [ ! -f $CM_BUILD_DIR/ipa/*.ipa ]; then
            echo "Creating unsigned IPA for AltStore/Sideloadly"
            cd $CM_BUILD_DIR

            APP_PATH="app.xcarchive/Products/Applications/NextcloudTalk.app"

            # Create Payload directory and package IPA
            mkdir -p Payload
            cp -r "$APP_PATH" Payload/

            # Create IPA (just a zip file)
            zip -qq -r -9 NextcloudTalk-unsigned.ipa Payload
            rm -rf Payload

            echo "✅ Unsigned IPA created: NextcloudTalk-unsigned.ipa"
            echo "📱 Install using AltStore, Sideloadly, or SideStore"
            echo "⚠️  This IPA needs to be re-signed with your Apple ID"
          else
            echo "IPA already exists from xcodebuild export"
          fi

    artifacts:
      - $CM_BUILD_DIR/app.xcarchive
      - $CM_BUILD_DIR/ipa/*.ipa
      - $CM_BUILD_DIR/*-unsigned.ipa
