workflows:
  ios-build-ipa:
    name: Build IPA
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "NextcloudTalk.xcworkspace"
        XCODE_SCHEME: "NextcloudTalk"
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: development
        bundle_identifier: com.nextcloud.Talk
    scripts:
      - name: Install dependencies
        script: |
          pod install

      - name: Set up code signing
        script: |
          keychain initialize

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_IDENTIFIER" \
            --type IOS_APP_DEVELOPMENT \
            --create

      - name: Add certificates to keychain
        script: |
          keychain add-certificates

      - name: Update project settings
        script: |
          xcode-project use-profiles

      - name: Build archive
        script: |
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/app.xcarchive \
            CODE_SIGN_STYLE=Manual \
            -allowProvisioningUpdates

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/app.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - $CM_BUILD_DIR/*.xcarchive
